import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";

const inter = Inter({ subsets: ["latin"] });

import profilePic from "../../public/images/profile/developer-pic-1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="codebucks"
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2">
              <h1>Turning Vision Into Reality With Code And Design.</h1>
              <p>
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications.{" "}
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
